### ISSUE TITLE
Healthcheck improvements

### ISSUE THREAD

**Issue by Beanow** [tauri-apps/tauri-discord-bot#103]
We have an HTTP healthcheck endpoint, but aren't using it.

https://docs.digitalocean.com/glossary/health-check/

https://docs.digitalocean.com/products/app-platform/reference/app-spec/#ref-services-health_check

**Comment by Beanow** [comment]
Actually we do have one, but probably good to have it in the repo.

```yaml
envs:
- key: DISCORD_TOKEN
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: ******
- key: NODE_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
name: tauri-discord-bot
region: lon
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: tauri-apps/tauri-discord-bot
  health_check:
    http_path: /api/v1/health
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: tauri-discord-bot
  routes:
  - path: /
  source_dir: /
```
